# Generated by Django 5.2.15 on 2026-06-14 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0002_terminalio'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='terminalio',
            new_name='terminals_t_termina_83330f_idx',
            old_name='terminals_t_termina_6f0f0d_idx',
        ),
    ]
